x-database-url: &database-url postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable

services:

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    entrypoint: [ "migrate", "-path", "/migrations", "-database", *database-url ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - matchmap-network

  api:
    build: .
    container_name: matchmap-api
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    environment:
      DATABASE_URL: *database-url
    depends_on:
      db:
        condition: service_healthy
    networks:
      - matchmap-network

  db:
    image: postgis/postgis:17-3.5
    container_name: matchmap-db
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    volumes:
      - matchmap-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - matchmap-network

volumes:
  matchmap-db-data:

networks:
  matchmap-network:
    driver: bridge
