services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: matchmap-api-dev

    ports:
      - "${APP_PORT}:8080"

    env_file:
      - .env

    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod

    depends_on:
      db:
        condition: service_healthy

    networks:
      - matchmap-network

volumes:
  go-mod-cache: